List<String> imagelist = [
  'images/home.png',
  'images/jops.png',
  'images/jops1.png',
  'images/contracts.png',
  'images/contracts.png',
  'images/typeofwork.png',
  'images/areport.png',
  'images/tripreport.png',
  'images/Inspectionreport.png',
  'images/dailytasks.png',
  'images/Vacationrequests.png',
  'images/DailyReport.png',
  'images/Vacationrequests.png',
];
List<String> gridtextlist = [
  'الرئيسية',
  'الموظفين',
  'الوظائف',
  'انواع العقود',
  'المشاريع',
  'نوع العمل',
  'تفرير العمل',
  'تقرير مشاوير المكتب',
  'تقرير المبيعات والمعاينات',
  'التقرير اليومي',
  'طلبات الاجازات',
  'المهام اليومية',
  'طلب اجازة',
];
